#!/bin/sh
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
NEWPATH="$(dirname "$(dirname "$SCRIPT_DIR")")/dbus-consumption-calculator.py"
exec 2>&1
exec python -u $NEWPATH
